queries:
  - include: "*"
  - exclude: cpp/short-global-name
extraction:
  cpp:
    prepare:
      packages:
        - python3.8
        - gnu-efi
        - nasm
    index:
      build_command:
        - python3.8 src/_build/main.py -k
  python:
    python_setup:
      requirements:
        - requests
      version: 3
