queries:
  - include: "*"
  - exclude: cpp/poorly-documented-function
  - exclude: cpp/short-global-name
  - exclude: java/index-out-of-bounds
  - exclude: java/local-shadows-field
  - exclude: java/potentially-weak-cryptographic-algorithm
  - exclude: java/uncaught-number-format-exception
  - exclude: java/unused-parameter
  - exclude: py/empty-except
  - exclude: py/redundant-global-declaration
extraction:
  cpp:
    prepare:
      packages:
        - python3.8
        - gnu-efi
        - nasm
    index:
      build_command:
        - python3.8 src/_build/main.py --rsrc --kernel
  python:
    python_setup:
      requirements:
        - requests
      version: 3
